version: '3'
services:
  # app:
  #   build: .
  #   ports:
  #     - ${SERVER_PORT}:3000
  #     - 9229:9229
  #   env_file:
  #     - .env
  postgresql:
    container_name: kiwiPostgresDb
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=kiwimanga
      - POSTGRES_PASSWORD=kiwimangapassword
      - POSTGRES_DB=kiwiManga
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  mongodb:
    container_name: kiwiMongoDb
    image: 'mongo:latest'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kiwimanga
      - MONGO_INITDB_ROOT_PASSWORD=kiwimangapassword
      - MONGO_INITDB_DATABASE=mangas
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'
volumes:
  postgres:
  mongo:
