version: '3'
name: kiwi-manga
services:
  postgresql:
    container_name: postgres
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=kiwimanga
      - POSTGRES_PASSWORD=kiwimangapassword
      - POSTGRES_DB=kiwiManga
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  redis:
    container_name: redis
    image: redis:latest
    command: redis-server --requirepass VM5kSd6A3qr
    ports:
      - "6379:6379"
  mongodb:
    container_name: mongodb
    image: 'mongo:latest'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kiwimanga
      - MONGO_INITDB_ROOT_PASSWORD=kiwimangapassword
      - MONGO_INITDB_DATABASE=mangas
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'
  app:
    container_name: api
    build: .
    ports:
      - 3333:3000
    env_file:
      - .env
volumes:
  postgres:
  mongo:
