export * from './auth.controller';
export * from './chapter.controller';
export * from './collections.controller';
export * from './favorites.controller';
export * from './health.controller';
export * from './mangas.controller';
export * from './profile-pic.controller';
export * from './score.controller';
export * from './users.controller';
